### ISSUE TITLE
HMC5883L Driver

### ISSUE THREAD

**Issue by cagdasc** [androidthings/contrib-drivers#9]
Hello,
I have a library written about 2 years ago. It's in my profile [HMC5883L](https://github.com/cagdasc/Linux-I2C). Now I add it on my local [repo](https://github.com/cagdasc/AndroidThings-HMC5883L) and forked [repo](https://github.com/cagdasc/contrib-drivers) for AndroidThings. I want to merge it. If it is ok, I will create pull request.

Thank you.
Good work.

**Comment by jdkoren** [comment]
Hi @cagdasc, we are happy to take contributions for new features or bug fixes on our existing drivers. For new drivers we generally suggest to host it on your own repo since it is entirely your work, so there is no need for a pull request. As was mentioned in #1, we do have future plans for indexing the various Android Things drivers to help aid discoverability. Thanks for your work :)
